import React, { createContext } from "react";

export const nurseData = createContext();
const Nursedata = ({ children }) => {
  const allrecipedData = [
    {
      id: 1,
      image: "https://picsum.photos/seed/recipe1/600/400",
      title: "Margherita Pizza #1",
      description:
        "A delicious french style margherita pizza made with fresh ingredients.",
      cookTime: "12 mins",
      cuisine: "Korean",
      difficulty: "Easy",
      calories: "406 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 2,
      image: "https://picsum.photos/seed/recipe2/600/400",
      title: "Chicken Biryani #2",
      description:
        "A delicious chinese style chicken biryani made with fresh ingredients.",
      cookTime: "70 mins",
      cuisine: "Mediterranean",
      difficulty: "Easy",
      calories: "288 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 3,
      image: "https://picsum.photos/seed/recipe3/600/400",
      title: "Paneer Butter Masala #3",
      description:
        "A delicious chinese style paneer butter masala made with fresh ingredients.",
      cookTime: "32 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "651 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 4,
      image: "https://picsum.photos/seed/recipe4/600/400",
      title: "Caesar Salad #4",
      description:
        "A delicious french style caesar salad made with fresh ingredients.",
      cookTime: "34 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "778 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 5,
      image: "https://picsum.photos/seed/recipe5/600/400",
      title: "Sushi Roll #5",
      description:
        "A delicious italian style sushi roll made with fresh ingredients.",
      cookTime: "43 mins",
      cuisine: "Chinese",
      difficulty: "Hard",
      calories: "592 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Garlic"],
    },
    {
      id: 6,
      image: "https://picsum.photos/seed/recipe6/600/400",
      title: "Pad Thai #6",
      description:
        "A delicious mexican style pad thai made with fresh ingredients.",
      cookTime: "43 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "608 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 7,
      image: "https://picsum.photos/seed/recipe7/600/400",
      title: "Butter Chicken #7",
      description:
        "A delicious mediterranean style butter chicken made with fresh ingredients.",
      cookTime: "71 mins",
      cuisine: "Thai",
      difficulty: "Hard",
      calories: "452 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Onion"],
    },
    {
      id: 8,
      image: "https://picsum.photos/seed/recipe8/600/400",
      title: "Tacos #8",
      description:
        "A delicious american style tacos made with fresh ingredients.",
      cookTime: "31 mins",
      cuisine: "Japanese",
      difficulty: "Medium",
      calories: "294 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Onion"],
    },
    {
      id: 9,
      image: "https://picsum.photos/seed/recipe9/600/400",
      title: "Veg Fried Rice #9",
      description:
        "A delicious french style veg fried rice made with fresh ingredients.",
      cookTime: "76 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "261 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Pepper"],
    },
    {
      id: 10,
      image: "https://picsum.photos/seed/recipe10/600/400",
      title: "Pasta Alfredo #10",
      description:
        "A delicious american style pasta alfredo made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "310 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 11,
      image: "https://picsum.photos/seed/recipe11/600/400",
      title: "Ramen #11",
      description:
        "A delicious indian style ramen made with fresh ingredients.",
      cookTime: "64 mins",
      cuisine: "Thai",
      difficulty: "Hard",
      calories: "347 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Olive Oil"],
    },
    {
      id: 12,
      image: "https://picsum.photos/seed/recipe12/600/400",
      title: "Falafel #12",
      description:
        "A delicious french style falafel made with fresh ingredients.",
      cookTime: "18 mins",
      cuisine: "Chinese",
      difficulty: "Hard",
      calories: "342 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Garlic"],
    },
    {
      id: 13,
      image: "https://picsum.photos/seed/recipe13/600/400",
      title: "Shawarma #13",
      description:
        "A delicious thai style shawarma made with fresh ingredients.",
      cookTime: "82 mins",
      cuisine: "Japanese",
      difficulty: "Easy",
      calories: "229 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 14,
      image: "https://picsum.photos/seed/recipe14/600/400",
      title: "Tom Yum Soup #14",
      description:
        "A delicious mexican style tom yum soup made with fresh ingredients.",
      cookTime: "42 mins",
      cuisine: "Thai",
      difficulty: "Hard",
      calories: "431 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Pepper"],
    },
    {
      id: 15,
      image: "https://picsum.photos/seed/recipe15/600/400",
      title: "Chocolate Cake #15",
      description:
        "A delicious american style chocolate cake made with fresh ingredients.",
      cookTime: "51 mins",
      cuisine: "Thai",
      difficulty: "Hard",
      calories: "439 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Onion"],
    },
    {
      id: 16,
      image: "https://picsum.photos/seed/recipe16/600/400",
      title: "Pancakes #16",
      description:
        "A delicious italian style pancakes made with fresh ingredients.",
      cookTime: "13 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "384 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
    {
      id: 17,
      image: "https://picsum.photos/seed/recipe17/600/400",
      title: "Burger #17",
      description:
        "A delicious mediterranean style burger made with fresh ingredients.",
      cookTime: "44 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "489 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 18,
      image: "https://picsum.photos/seed/recipe18/600/400",
      title: "Grilled Salmon #18",
      description:
        "A delicious italian style grilled salmon made with fresh ingredients.",
      cookTime: "69 mins",
      cuisine: "Mexican",
      difficulty: "Hard",
      calories: "609 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Pepper"],
    },
    {
      id: 19,
      image: "https://picsum.photos/seed/recipe19/600/400",
      title: "Momos #19",
      description:
        "A delicious chinese style momos made with fresh ingredients.",
      cookTime: "62 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "725 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Onion"],
    },
    {
      id: 20,
      image: "https://picsum.photos/seed/recipe20/600/400",
      title: "Dosa #20",
      description:
        "A delicious mediterranean style dosa made with fresh ingredients.",
      cookTime: "43 mins",
      cuisine: "Mexican",
      difficulty: "Hard",
      calories: "579 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Pepper"],
    },
    {
      id: 21,
      image: "https://picsum.photos/seed/recipe21/600/400",
      title: "Margherita Pizza #21",
      description:
        "A delicious italian style margherita pizza made with fresh ingredients.",
      cookTime: "38 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "521 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 22,
      image: "https://picsum.photos/seed/recipe22/600/400",
      title: "Chicken Biryani #22",
      description:
        "A delicious indian style chicken biryani made with fresh ingredients.",
      cookTime: "59 mins",
      cuisine: "Indian",
      difficulty: "Medium",
      calories: "374 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 23,
      image: "https://picsum.photos/seed/recipe23/600/400",
      title: "Paneer Butter Masala #23",
      description:
        "A delicious japanese style paneer butter masala made with fresh ingredients.",
      cookTime: "12 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "428 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 24,
      image: "https://picsum.photos/seed/recipe24/600/400",
      title: "Caesar Salad #24",
      description:
        "A delicious korean style caesar salad made with fresh ingredients.",
      cookTime: "78 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "827 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
    {
      id: 25,
      image: "https://picsum.photos/seed/recipe25/600/400",
      title: "Sushi Roll #25",
      description:
        "A delicious korean style sushi roll made with fresh ingredients.",
      cookTime: "26 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "619 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 26,
      image: "https://picsum.photos/seed/recipe26/600/400",
      title: "Pad Thai #26",
      description:
        "A delicious italian style pad thai made with fresh ingredients.",
      cookTime: "14 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "336 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Herbs"],
    },
    {
      id: 27,
      image: "https://picsum.photos/seed/recipe27/600/400",
      title: "Butter Chicken #27",
      description:
        "A delicious american style butter chicken made with fresh ingredients.",
      cookTime: "72 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "413 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 28,
      image: "https://picsum.photos/seed/recipe28/600/400",
      title: "Tacos #28",
      description:
        "A delicious korean style tacos made with fresh ingredients.",
      cookTime: "80 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "305 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Garlic"],
    },
    {
      id: 29,
      image: "https://picsum.photos/seed/recipe29/600/400",
      title: "Veg Fried Rice #29",
      description:
        "A delicious korean style veg fried rice made with fresh ingredients.",
      cookTime: "85 mins",
      cuisine: "Italian",
      difficulty: "Easy",
      calories: "640 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 30,
      image: "https://picsum.photos/seed/recipe30/600/400",
      title: "Pasta Alfredo #30",
      description:
        "A delicious mexican style pasta alfredo made with fresh ingredients.",
      cookTime: "22 mins",
      cuisine: "Chinese",
      difficulty: "Medium",
      calories: "695 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Garlic"],
    },
    {
      id: 31,
      image: "https://picsum.photos/seed/recipe31/600/400",
      title: "Ramen #31",
      description:
        "A delicious indian style ramen made with fresh ingredients.",
      cookTime: "52 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "589 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
    {
      id: 32,
      image: "https://picsum.photos/seed/recipe32/600/400",
      title: "Falafel #32",
      description:
        "A delicious french style falafel made with fresh ingredients.",
      cookTime: "19 mins",
      cuisine: "Thai",
      difficulty: "Easy",
      calories: "230 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Onion"],
    },
    {
      id: 33,
      image: "https://picsum.photos/seed/recipe33/600/400",
      title: "Shawarma #33",
      description:
        "A delicious thai style shawarma made with fresh ingredients.",
      cookTime: "71 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "510 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Pepper"],
    },
    {
      id: 34,
      image: "https://picsum.photos/seed/recipe34/600/400",
      title: "Tom Yum Soup #34",
      description:
        "A delicious american style tom yum soup made with fresh ingredients.",
      cookTime: "73 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "712 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 35,
      image: "https://picsum.photos/seed/recipe35/600/400",
      title: "Chocolate Cake #35",
      description:
        "A delicious korean style chocolate cake made with fresh ingredients.",
      cookTime: "81 mins",
      cuisine: "Chinese",
      difficulty: "Hard",
      calories: "795 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Garlic"],
    },
    {
      id: 36,
      image: "https://picsum.photos/seed/recipe36/600/400",
      title: "Pancakes #36",
      description:
        "A delicious chinese style pancakes made with fresh ingredients.",
      cookTime: "35 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "457 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 37,
      image: "https://picsum.photos/seed/recipe37/600/400",
      title: "Burger #37",
      description:
        "A delicious french style burger made with fresh ingredients.",
      cookTime: "74 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "544 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 38,
      image: "https://picsum.photos/seed/recipe38/600/400",
      title: "Grilled Salmon #38",
      description:
        "A delicious japanese style grilled salmon made with fresh ingredients.",
      cookTime: "58 mins",
      cuisine: "Italian",
      difficulty: "Medium",
      calories: "223 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Onion"],
    },
    {
      id: 39,
      image: "https://picsum.photos/seed/recipe39/600/400",
      title: "Momos #39",
      description:
        "A delicious french style momos made with fresh ingredients.",
      cookTime: "61 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "395 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 40,
      image: "https://picsum.photos/seed/recipe40/600/400",
      title: "Dosa #40",
      description:
        "A delicious italian style dosa made with fresh ingredients.",
      cookTime: "71 mins",
      cuisine: "Korean",
      difficulty: "Easy",
      calories: "501 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 41,
      image: "https://picsum.photos/seed/recipe41/600/400",
      title: "Margherita Pizza #41",
      description:
        "A delicious mediterranean style margherita pizza made with fresh ingredients.",
      cookTime: "27 mins",
      cuisine: "Italian",
      difficulty: "Easy",
      calories: "847 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Garlic"],
    },
    {
      id: 42,
      image: "https://picsum.photos/seed/recipe42/600/400",
      title: "Chicken Biryani #42",
      description:
        "A delicious chinese style chicken biryani made with fresh ingredients.",
      cookTime: "31 mins",
      cuisine: "Thai",
      difficulty: "Easy",
      calories: "209 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 43,
      image: "https://picsum.photos/seed/recipe43/600/400",
      title: "Paneer Butter Masala #43",
      description:
        "A delicious korean style paneer butter masala made with fresh ingredients.",
      cookTime: "89 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "336 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Herbs"],
    },
    {
      id: 44,
      image: "https://picsum.photos/seed/recipe44/600/400",
      title: "Caesar Salad #44",
      description:
        "A delicious thai style caesar salad made with fresh ingredients.",
      cookTime: "88 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "240 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 45,
      image: "https://picsum.photos/seed/recipe45/600/400",
      title: "Sushi Roll #45",
      description:
        "A delicious korean style sushi roll made with fresh ingredients.",
      cookTime: "86 mins",
      cuisine: "Korean",
      difficulty: "Easy",
      calories: "373 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Garlic"],
    },
    {
      id: 46,
      image: "https://picsum.photos/seed/recipe46/600/400",
      title: "Pad Thai #46",
      description:
        "A delicious mexican style pad thai made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Italian",
      difficulty: "Medium",
      calories: "500 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 47,
      image: "https://picsum.photos/seed/recipe47/600/400",
      title: "Butter Chicken #47",
      description:
        "A delicious chinese style butter chicken made with fresh ingredients.",
      cookTime: "48 mins",
      cuisine: "Mediterranean",
      difficulty: "Hard",
      calories: "813 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 48,
      image: "https://picsum.photos/seed/recipe48/600/400",
      title: "Tacos #48",
      description: "A delicious thai style tacos made with fresh ingredients.",
      cookTime: "77 mins",
      cuisine: "Italian",
      difficulty: "Medium",
      calories: "780 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 49,
      image: "https://picsum.photos/seed/recipe49/600/400",
      title: "Veg Fried Rice #49",
      description:
        "A delicious american style veg fried rice made with fresh ingredients.",
      cookTime: "47 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "219 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 50,
      image: "https://picsum.photos/seed/recipe50/600/400",
      title: "Pasta Alfredo #50",
      description:
        "A delicious japanese style pasta alfredo made with fresh ingredients.",
      cookTime: "78 mins",
      cuisine: "Mediterranean",
      difficulty: "Easy",
      calories: "356 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Olive Oil"],
    },
    {
      id: 51,
      image: "https://picsum.photos/seed/recipe51/600/400",
      title: "Ramen #51",
      description:
        "A delicious mexican style ramen made with fresh ingredients.",
      cookTime: "38 mins",
      cuisine: "Mediterranean",
      difficulty: "Easy",
      calories: "564 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 52,
      image: "https://picsum.photos/seed/recipe52/600/400",
      title: "Falafel #52",
      description:
        "A delicious chinese style falafel made with fresh ingredients.",
      cookTime: "24 mins",
      cuisine: "Japanese",
      difficulty: "Medium",
      calories: "441 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 53,
      image: "https://picsum.photos/seed/recipe53/600/400",
      title: "Shawarma #53",
      description:
        "A delicious chinese style shawarma made with fresh ingredients.",
      cookTime: "72 mins",
      cuisine: "Mediterranean",
      difficulty: "Hard",
      calories: "206 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 54,
      image: "https://picsum.photos/seed/recipe54/600/400",
      title: "Tom Yum Soup #54",
      description:
        "A delicious korean style tom yum soup made with fresh ingredients.",
      cookTime: "86 mins",
      cuisine: "Korean",
      difficulty: "Hard",
      calories: "632 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 55,
      image: "https://picsum.photos/seed/recipe55/600/400",
      title: "Chocolate Cake #55",
      description:
        "A delicious korean style chocolate cake made with fresh ingredients.",
      cookTime: "85 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "341 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 56,
      image: "https://picsum.photos/seed/recipe56/600/400",
      title: "Pancakes #56",
      description:
        "A delicious thai style pancakes made with fresh ingredients.",
      cookTime: "15 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "829 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Herbs"],
    },
    {
      id: 57,
      image: "https://picsum.photos/seed/recipe57/600/400",
      title: "Burger #57",
      description:
        "A delicious american style burger made with fresh ingredients.",
      cookTime: "36 mins",
      cuisine: "Japanese",
      difficulty: "Medium",
      calories: "836 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 58,
      image: "https://picsum.photos/seed/recipe58/600/400",
      title: "Grilled Salmon #58",
      description:
        "A delicious french style grilled salmon made with fresh ingredients.",
      cookTime: "89 mins",
      cuisine: "American",
      difficulty: "Medium",
      calories: "361 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Garlic"],
    },
    {
      id: 59,
      image: "https://picsum.photos/seed/recipe59/600/400",
      title: "Momos #59",
      description:
        "A delicious indian style momos made with fresh ingredients.",
      cookTime: "14 mins",
      cuisine: "Italian",
      difficulty: "Easy",
      calories: "742 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Garlic"],
    },
    {
      id: 60,
      image: "https://picsum.photos/seed/recipe60/600/400",
      title: "Dosa #60",
      description: "A delicious thai style dosa made with fresh ingredients.",
      cookTime: "22 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "188 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Onion"],
    },
    {
      id: 61,
      image: "https://picsum.photos/seed/recipe61/600/400",
      title: "Margherita Pizza #61",
      description:
        "A delicious indian style margherita pizza made with fresh ingredients.",
      cookTime: "65 mins",
      cuisine: "Chinese",
      difficulty: "Medium",
      calories: "682 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 62,
      image: "https://picsum.photos/seed/recipe62/600/400",
      title: "Chicken Biryani #62",
      description:
        "A delicious japanese style chicken biryani made with fresh ingredients.",
      cookTime: "76 mins",
      cuisine: "Korean",
      difficulty: "Hard",
      calories: "454 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 63,
      image: "https://picsum.photos/seed/recipe63/600/400",
      title: "Paneer Butter Masala #63",
      description:
        "A delicious american style paneer butter masala made with fresh ingredients.",
      cookTime: "60 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "599 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Garlic"],
    },
    {
      id: 64,
      image: "https://picsum.photos/seed/recipe64/600/400",
      title: "Caesar Salad #64",
      description:
        "A delicious korean style caesar salad made with fresh ingredients.",
      cookTime: "67 mins",
      cuisine: "Mexican",
      difficulty: "Hard",
      calories: "193 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 65,
      image: "https://picsum.photos/seed/recipe65/600/400",
      title: "Sushi Roll #65",
      description:
        "A delicious french style sushi roll made with fresh ingredients.",
      cookTime: "20 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "769 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Garlic"],
    },
    {
      id: 66,
      image: "https://picsum.photos/seed/recipe66/600/400",
      title: "Pad Thai #66",
      description:
        "A delicious mediterranean style pad thai made with fresh ingredients.",
      cookTime: "59 mins",
      cuisine: "Mexican",
      difficulty: "Medium",
      calories: "787 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Garlic"],
    },
    {
      id: 67,
      image: "https://picsum.photos/seed/recipe67/600/400",
      title: "Butter Chicken #67",
      description:
        "A delicious japanese style butter chicken made with fresh ingredients.",
      cookTime: "42 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "781 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 68,
      image: "https://picsum.photos/seed/recipe68/600/400",
      title: "Tacos #68",
      description:
        "A delicious mexican style tacos made with fresh ingredients.",
      cookTime: "61 mins",
      cuisine: "Mediterranean",
      difficulty: "Easy",
      calories: "313 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 69,
      image: "https://picsum.photos/seed/recipe69/600/400",
      title: "Veg Fried Rice #69",
      description:
        "A delicious indian style veg fried rice made with fresh ingredients.",
      cookTime: "58 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "844 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Pepper"],
    },
    {
      id: 70,
      image: "https://picsum.photos/seed/recipe70/600/400",
      title: "Pasta Alfredo #70",
      description:
        "A delicious korean style pasta alfredo made with fresh ingredients.",
      cookTime: "44 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "835 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Garlic"],
    },
    {
      id: 71,
      image: "https://picsum.photos/seed/recipe71/600/400",
      title: "Ramen #71",
      description:
        "A delicious chinese style ramen made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "814 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 72,
      image: "https://picsum.photos/seed/recipe72/600/400",
      title: "Falafel #72",
      description:
        "A delicious french style falafel made with fresh ingredients.",
      cookTime: "77 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "458 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Pepper"],
    },
    {
      id: 73,
      image: "https://picsum.photos/seed/recipe73/600/400",
      title: "Shawarma #73",
      description:
        "A delicious thai style shawarma made with fresh ingredients.",
      cookTime: "72 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "652 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Pepper"],
    },
    {
      id: 74,
      image: "https://picsum.photos/seed/recipe74/600/400",
      title: "Tom Yum Soup #74",
      description:
        "A delicious italian style tom yum soup made with fresh ingredients.",
      cookTime: "37 mins",
      cuisine: "Japanese",
      difficulty: "Medium",
      calories: "713 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
    {
      id: 75,
      image: "https://picsum.photos/seed/recipe75/600/400",
      title: "Chocolate Cake #75",
      description:
        "A delicious italian style chocolate cake made with fresh ingredients.",
      cookTime: "51 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "222 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 76,
      image: "https://picsum.photos/seed/recipe76/600/400",
      title: "Pancakes #76",
      description:
        "A delicious american style pancakes made with fresh ingredients.",
      cookTime: "65 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "420 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Pepper"],
    },
    {
      id: 77,
      image: "https://picsum.photos/seed/recipe77/600/400",
      title: "Burger #77",
      description:
        "A delicious italian style burger made with fresh ingredients.",
      cookTime: "12 mins",
      cuisine: "Mediterranean",
      difficulty: "Hard",
      calories: "739 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Pepper"],
    },
    {
      id: 78,
      image: "https://picsum.photos/seed/recipe78/600/400",
      title: "Grilled Salmon #78",
      description:
        "A delicious chinese style grilled salmon made with fresh ingredients.",
      cookTime: "47 mins",
      cuisine: "Chinese",
      difficulty: "Medium",
      calories: "377 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 79,
      image: "https://picsum.photos/seed/recipe79/600/400",
      title: "Momos #79",
      description:
        "A delicious american style momos made with fresh ingredients.",
      cookTime: "62 mins",
      cuisine: "Indian",
      difficulty: "Easy",
      calories: "435 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 80,
      image: "https://picsum.photos/seed/recipe80/600/400",
      title: "Dosa #80",
      description:
        "A delicious italian style dosa made with fresh ingredients.",
      cookTime: "42 mins",
      cuisine: "Korean",
      difficulty: "Easy",
      calories: "771 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Pepper"],
    },
    {
      id: 81,
      image: "https://picsum.photos/seed/recipe81/600/400",
      title: "Margherita Pizza #81",
      description:
        "A delicious mediterranean style margherita pizza made with fresh ingredients.",
      cookTime: "27 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "398 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 82,
      image: "https://picsum.photos/seed/recipe82/600/400",
      title: "Chicken Biryani #82",
      description:
        "A delicious french style chicken biryani made with fresh ingredients.",
      cookTime: "15 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "645 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Herbs"],
    },
    {
      id: 83,
      image: "https://picsum.photos/seed/recipe83/600/400",
      title: "Paneer Butter Masala #83",
      description:
        "A delicious italian style paneer butter masala made with fresh ingredients.",
      cookTime: "37 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "658 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 84,
      image: "https://picsum.photos/seed/recipe84/600/400",
      title: "Caesar Salad #84",
      description:
        "A delicious indian style caesar salad made with fresh ingredients.",
      cookTime: "66 mins",
      cuisine: "Italian",
      difficulty: "Medium",
      calories: "727 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Garlic"],
    },
    {
      id: 85,
      image: "https://picsum.photos/seed/recipe85/600/400",
      title: "Sushi Roll #85",
      description:
        "A delicious chinese style sushi roll made with fresh ingredients.",
      cookTime: "49 mins",
      cuisine: "Chinese",
      difficulty: "Hard",
      calories: "774 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Pepper"],
    },
    {
      id: 86,
      image: "https://picsum.photos/seed/recipe86/600/400",
      title: "Pad Thai #86",
      description:
        "A delicious indian style pad thai made with fresh ingredients.",
      cookTime: "55 mins",
      cuisine: "Korean",
      difficulty: "Hard",
      calories: "659 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
    {
      id: 87,
      image: "https://picsum.photos/seed/recipe87/600/400",
      title: "Butter Chicken #87",
      description:
        "A delicious french style butter chicken made with fresh ingredients.",
      cookTime: "32 mins",
      cuisine: "French",
      difficulty: "Easy",
      calories: "794 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 88,
      image: "https://picsum.photos/seed/recipe88/600/400",
      title: "Tacos #88",
      description:
        "A delicious american style tacos made with fresh ingredients.",
      cookTime: "87 mins",
      cuisine: "Mediterranean",
      difficulty: "Hard",
      calories: "711 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 89,
      image: "https://picsum.photos/seed/recipe89/600/400",
      title: "Veg Fried Rice #89",
      description:
        "A delicious korean style veg fried rice made with fresh ingredients.",
      cookTime: "88 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "240 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 90,
      image: "https://picsum.photos/seed/recipe90/600/400",
      title: "Pasta Alfredo #90",
      description:
        "A delicious thai style pasta alfredo made with fresh ingredients.",
      cookTime: "51 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "325 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 91,
      image: "https://picsum.photos/seed/recipe91/600/400",
      title: "Ramen #91",
      description:
        "A delicious italian style ramen made with fresh ingredients.",
      cookTime: "23 mins",
      cuisine: "Italian",
      difficulty: "Easy",
      calories: "775 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Pepper"],
    },
    {
      id: 92,
      image: "https://picsum.photos/seed/recipe92/600/400",
      title: "Falafel #92",
      description:
        "A delicious mexican style falafel made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "709 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 93,
      image: "https://picsum.photos/seed/recipe93/600/400",
      title: "Shawarma #93",
      description:
        "A delicious korean style shawarma made with fresh ingredients.",
      cookTime: "12 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "738 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Garlic"],
    },
    {
      id: 94,
      image: "https://picsum.photos/seed/recipe94/600/400",
      title: "Tom Yum Soup #94",
      description:
        "A delicious chinese style tom yum soup made with fresh ingredients.",
      cookTime: "65 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "818 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Olive Oil"],
    },
    {
      id: 95,
      image: "https://picsum.photos/seed/recipe95/600/400",
      title: "Chocolate Cake #95",
      description:
        "A delicious thai style chocolate cake made with fresh ingredients.",
      cookTime: "68 mins",
      cuisine: "Chinese",
      difficulty: "Hard",
      calories: "218 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Onion"],
    },
    {
      id: 96,
      image: "https://picsum.photos/seed/recipe96/600/400",
      title: "Pancakes #96",
      description:
        "A delicious chinese style pancakes made with fresh ingredients.",
      cookTime: "49 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "515 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 97,
      image: "https://picsum.photos/seed/recipe97/600/400",
      title: "Burger #97",
      description:
        "A delicious indian style burger made with fresh ingredients.",
      cookTime: "11 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "629 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Pepper"],
    },
    {
      id: 98,
      image: "https://picsum.photos/seed/recipe98/600/400",
      title: "Grilled Salmon #98",
      description:
        "A delicious japanese style grilled salmon made with fresh ingredients.",
      cookTime: "12 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "244 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 99,
      image: "https://picsum.photos/seed/recipe99/600/400",
      title: "Momos #99",
      description:
        "A delicious chinese style momos made with fresh ingredients.",
      cookTime: "66 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "190 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Onion"],
    },
    {
      id: 100,
      image: "https://picsum.photos/seed/recipe100/600/400",
      title: "Dosa #100",
      description:
        "A delicious italian style dosa made with fresh ingredients.",
      cookTime: "43 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "776 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Onion"],
    },
    {
      id: 101,
      image: "https://picsum.photos/seed/recipe101/600/400",
      title: "Margherita Pizza #101",
      description:
        "A delicious mexican style margherita pizza made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Mexican",
      difficulty: "Medium",
      calories: "587 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Olive Oil"],
    },
    {
      id: 102,
      image: "https://picsum.photos/seed/recipe102/600/400",
      title: "Chicken Biryani #102",
      description:
        "A delicious korean style chicken biryani made with fresh ingredients.",
      cookTime: "31 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "525 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Onion"],
    },
    {
      id: 103,
      image: "https://picsum.photos/seed/recipe103/600/400",
      title: "Paneer Butter Masala #103",
      description:
        "A delicious japanese style paneer butter masala made with fresh ingredients.",
      cookTime: "20 mins",
      cuisine: "Mediterranean",
      difficulty: "Easy",
      calories: "214 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 104,
      image: "https://picsum.photos/seed/recipe104/600/400",
      title: "Caesar Salad #104",
      description:
        "A delicious chinese style caesar salad made with fresh ingredients.",
      cookTime: "57 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "458 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 105,
      image: "https://picsum.photos/seed/recipe105/600/400",
      title: "Sushi Roll #105",
      description:
        "A delicious american style sushi roll made with fresh ingredients.",
      cookTime: "65 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "670 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Olive Oil"],
    },
    {
      id: 106,
      image: "https://picsum.photos/seed/recipe106/600/400",
      title: "Pad Thai #106",
      description:
        "A delicious french style pad thai made with fresh ingredients.",
      cookTime: "70 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "521 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 107,
      image: "https://picsum.photos/seed/recipe107/600/400",
      title: "Butter Chicken #107",
      description:
        "A delicious japanese style butter chicken made with fresh ingredients.",
      cookTime: "61 mins",
      cuisine: "Chinese",
      difficulty: "Medium",
      calories: "818 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
    {
      id: 108,
      image: "https://picsum.photos/seed/recipe108/600/400",
      title: "Tacos #108",
      description:
        "A delicious mediterranean style tacos made with fresh ingredients.",
      cookTime: "54 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "550 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 109,
      image: "https://picsum.photos/seed/recipe109/600/400",
      title: "Veg Fried Rice #109",
      description:
        "A delicious mediterranean style veg fried rice made with fresh ingredients.",
      cookTime: "57 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "400 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Pepper"],
    },
    {
      id: 110,
      image: "https://picsum.photos/seed/recipe110/600/400",
      title: "Pasta Alfredo #110",
      description:
        "A delicious japanese style pasta alfredo made with fresh ingredients.",
      cookTime: "41 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "558 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Onion"],
    },
    {
      id: 111,
      image: "https://picsum.photos/seed/recipe111/600/400",
      title: "Ramen #111",
      description:
        "A delicious chinese style ramen made with fresh ingredients.",
      cookTime: "36 mins",
      cuisine: "Chinese",
      difficulty: "Medium",
      calories: "532 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 112,
      image: "https://picsum.photos/seed/recipe112/600/400",
      title: "Falafel #112",
      description:
        "A delicious japanese style falafel made with fresh ingredients.",
      cookTime: "82 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "247 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Onion"],
    },
    {
      id: 113,
      image: "https://picsum.photos/seed/recipe113/600/400",
      title: "Shawarma #113",
      description:
        "A delicious mediterranean style shawarma made with fresh ingredients.",
      cookTime: "88 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "703 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Olive Oil"],
    },
    {
      id: 114,
      image: "https://picsum.photos/seed/recipe114/600/400",
      title: "Tom Yum Soup #114",
      description:
        "A delicious american style tom yum soup made with fresh ingredients.",
      cookTime: "12 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "284 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Onion"],
    },
    {
      id: 115,
      image: "https://picsum.photos/seed/recipe115/600/400",
      title: "Chocolate Cake #115",
      description:
        "A delicious italian style chocolate cake made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Korean",
      difficulty: "Easy",
      calories: "788 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 116,
      image: "https://picsum.photos/seed/recipe116/600/400",
      title: "Pancakes #116",
      description:
        "A delicious indian style pancakes made with fresh ingredients.",
      cookTime: "77 mins",
      cuisine: "French",
      difficulty: "Hard",
      calories: "188 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Pepper"],
    },
    {
      id: 117,
      image: "https://picsum.photos/seed/recipe117/600/400",
      title: "Burger #117",
      description:
        "A delicious american style burger made with fresh ingredients.",
      cookTime: "54 mins",
      cuisine: "Japanese",
      difficulty: "Medium",
      calories: "194 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Garlic"],
    },
    {
      id: 118,
      image: "https://picsum.photos/seed/recipe118/600/400",
      title: "Grilled Salmon #118",
      description:
        "A delicious korean style grilled salmon made with fresh ingredients.",
      cookTime: "28 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "456 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Garlic"],
    },
    {
      id: 119,
      image: "https://picsum.photos/seed/recipe119/600/400",
      title: "Momos #119",
      description:
        "A delicious american style momos made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "227 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Olive Oil"],
    },
    {
      id: 120,
      image: "https://picsum.photos/seed/recipe120/600/400",
      title: "Dosa #120",
      description: "A delicious korean style dosa made with fresh ingredients.",
      cookTime: "37 mins",
      cuisine: "Mexican",
      difficulty: "Hard",
      calories: "389 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Garlic"],
    },
    {
      id: 121,
      image: "https://picsum.photos/seed/recipe121/600/400",
      title: "Margherita Pizza #121",
      description:
        "A delicious mexican style margherita pizza made with fresh ingredients.",
      cookTime: "27 mins",
      cuisine: "Thai",
      difficulty: "Hard",
      calories: "796 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Herbs"],
    },
    {
      id: 122,
      image: "https://picsum.photos/seed/recipe122/600/400",
      title: "Chicken Biryani #122",
      description:
        "A delicious thai style chicken biryani made with fresh ingredients.",
      cookTime: "85 mins",
      cuisine: "Italian",
      difficulty: "Medium",
      calories: "429 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Onion"],
    },
    {
      id: 123,
      image: "https://picsum.photos/seed/recipe123/600/400",
      title: "Paneer Butter Masala #123",
      description:
        "A delicious chinese style paneer butter masala made with fresh ingredients.",
      cookTime: "44 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "353 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Onion"],
    },
    {
      id: 124,
      image: "https://picsum.photos/seed/recipe124/600/400",
      title: "Caesar Salad #124",
      description:
        "A delicious american style caesar salad made with fresh ingredients.",
      cookTime: "37 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "363 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 125,
      image: "https://picsum.photos/seed/recipe125/600/400",
      title: "Sushi Roll #125",
      description:
        "A delicious indian style sushi roll made with fresh ingredients.",
      cookTime: "44 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "749 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 126,
      image: "https://picsum.photos/seed/recipe126/600/400",
      title: "Pad Thai #126",
      description:
        "A delicious french style pad thai made with fresh ingredients.",
      cookTime: "27 mins",
      cuisine: "Thai",
      difficulty: "Hard",
      calories: "386 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Pepper"],
    },
    {
      id: 127,
      image: "https://picsum.photos/seed/recipe127/600/400",
      title: "Butter Chicken #127",
      description:
        "A delicious american style butter chicken made with fresh ingredients.",
      cookTime: "88 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "382 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Olive Oil"],
    },
    {
      id: 128,
      image: "https://picsum.photos/seed/recipe128/600/400",
      title: "Tacos #128",
      description:
        "A delicious american style tacos made with fresh ingredients.",
      cookTime: "38 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "583 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Onion"],
    },
    {
      id: 129,
      image: "https://picsum.photos/seed/recipe129/600/400",
      title: "Veg Fried Rice #129",
      description:
        "A delicious thai style veg fried rice made with fresh ingredients.",
      cookTime: "37 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "692 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 130,
      image: "https://picsum.photos/seed/recipe130/600/400",
      title: "Pasta Alfredo #130",
      description:
        "A delicious thai style pasta alfredo made with fresh ingredients.",
      cookTime: "46 mins",
      cuisine: "Italian",
      difficulty: "Easy",
      calories: "529 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 131,
      image: "https://picsum.photos/seed/recipe131/600/400",
      title: "Ramen #131",
      description:
        "A delicious chinese style ramen made with fresh ingredients.",
      cookTime: "20 mins",
      cuisine: "Indian",
      difficulty: "Hard",
      calories: "220 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 132,
      image: "https://picsum.photos/seed/recipe132/600/400",
      title: "Falafel #132",
      description:
        "A delicious chinese style falafel made with fresh ingredients.",
      cookTime: "17 mins",
      cuisine: "Italian",
      difficulty: "Easy",
      calories: "762 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 133,
      image: "https://picsum.photos/seed/recipe133/600/400",
      title: "Shawarma #133",
      description:
        "A delicious chinese style shawarma made with fresh ingredients.",
      cookTime: "37 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "187 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 134,
      image: "https://picsum.photos/seed/recipe134/600/400",
      title: "Tom Yum Soup #134",
      description:
        "A delicious indian style tom yum soup made with fresh ingredients.",
      cookTime: "38 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "675 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Garlic"],
    },
    {
      id: 135,
      image: "https://picsum.photos/seed/recipe135/600/400",
      title: "Chocolate Cake #135",
      description:
        "A delicious french style chocolate cake made with fresh ingredients.",
      cookTime: "48 mins",
      cuisine: "Indian",
      difficulty: "Medium",
      calories: "494 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 136,
      image: "https://picsum.photos/seed/recipe136/600/400",
      title: "Pancakes #136",
      description:
        "A delicious japanese style pancakes made with fresh ingredients.",
      cookTime: "52 mins",
      cuisine: "Japanese",
      difficulty: "Easy",
      calories: "827 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 137,
      image: "https://picsum.photos/seed/recipe137/600/400",
      title: "Burger #137",
      description:
        "A delicious mexican style burger made with fresh ingredients.",
      cookTime: "85 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "587 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Olive Oil"],
    },
    {
      id: 138,
      image: "https://picsum.photos/seed/recipe138/600/400",
      title: "Grilled Salmon #138",
      description:
        "A delicious japanese style grilled salmon made with fresh ingredients.",
      cookTime: "89 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "530 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Onion"],
    },
    {
      id: 139,
      image: "https://picsum.photos/seed/recipe139/600/400",
      title: "Momos #139",
      description: "A delicious thai style momos made with fresh ingredients.",
      cookTime: "42 mins",
      cuisine: "Korean",
      difficulty: "Easy",
      calories: "348 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 140,
      image: "https://picsum.photos/seed/recipe140/600/400",
      title: "Dosa #140",
      description: "A delicious french style dosa made with fresh ingredients.",
      cookTime: "35 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "749 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 141,
      image: "https://picsum.photos/seed/recipe141/600/400",
      title: "Margherita Pizza #141",
      description:
        "A delicious american style margherita pizza made with fresh ingredients.",
      cookTime: "33 mins",
      cuisine: "Mexican",
      difficulty: "Medium",
      calories: "517 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Olive Oil"],
    },
    {
      id: 142,
      image: "https://picsum.photos/seed/recipe142/600/400",
      title: "Chicken Biryani #142",
      description:
        "A delicious chinese style chicken biryani made with fresh ingredients.",
      cookTime: "28 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "596 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Olive Oil"],
    },
    {
      id: 143,
      image: "https://picsum.photos/seed/recipe143/600/400",
      title: "Paneer Butter Masala #143",
      description:
        "A delicious mediterranean style paneer butter masala made with fresh ingredients.",
      cookTime: "45 mins",
      cuisine: "Thai",
      difficulty: "Easy",
      calories: "204 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Olive Oil"],
    },
    {
      id: 144,
      image: "https://picsum.photos/seed/recipe144/600/400",
      title: "Caesar Salad #144",
      description:
        "A delicious american style caesar salad made with fresh ingredients.",
      cookTime: "30 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "547 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Onion"],
    },
    {
      id: 145,
      image: "https://picsum.photos/seed/recipe145/600/400",
      title: "Sushi Roll #145",
      description:
        "A delicious italian style sushi roll made with fresh ingredients.",
      cookTime: "58 mins",
      cuisine: "Chinese",
      difficulty: "Medium",
      calories: "620 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Olive Oil"],
    },
    {
      id: 146,
      image: "https://picsum.photos/seed/recipe146/600/400",
      title: "Pad Thai #146",
      description:
        "A delicious american style pad thai made with fresh ingredients.",
      cookTime: "20 mins",
      cuisine: "Thai",
      difficulty: "Easy",
      calories: "243 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 147,
      image: "https://picsum.photos/seed/recipe147/600/400",
      title: "Butter Chicken #147",
      description:
        "A delicious mexican style butter chicken made with fresh ingredients.",
      cookTime: "71 mins",
      cuisine: "Indian",
      difficulty: "Easy",
      calories: "589 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 148,
      image: "https://picsum.photos/seed/recipe148/600/400",
      title: "Tacos #148",
      description:
        "A delicious american style tacos made with fresh ingredients.",
      cookTime: "89 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "790 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 149,
      image: "https://picsum.photos/seed/recipe149/600/400",
      title: "Veg Fried Rice #149",
      description:
        "A delicious mexican style veg fried rice made with fresh ingredients.",
      cookTime: "41 mins",
      cuisine: "Mediterranean",
      difficulty: "Hard",
      calories: "486 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 150,
      image: "https://picsum.photos/seed/recipe150/600/400",
      title: "Pasta Alfredo #150",
      description:
        "A delicious thai style pasta alfredo made with fresh ingredients.",
      cookTime: "50 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "773 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
    {
      id: 151,
      image: "https://picsum.photos/seed/recipe151/600/400",
      title: "Ramen #151",
      description:
        "A delicious japanese style ramen made with fresh ingredients.",
      cookTime: "50 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "401 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Herbs"],
    },
    {
      id: 152,
      image: "https://picsum.photos/seed/recipe152/600/400",
      title: "Falafel #152",
      description:
        "A delicious indian style falafel made with fresh ingredients.",
      cookTime: "29 mins",
      cuisine: "Italian",
      difficulty: "Easy",
      calories: "256 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Olive Oil"],
    },
    {
      id: 153,
      image: "https://picsum.photos/seed/recipe153/600/400",
      title: "Shawarma #153",
      description:
        "A delicious mexican style shawarma made with fresh ingredients.",
      cookTime: "38 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "587 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Pepper"],
    },
    {
      id: 154,
      image: "https://picsum.photos/seed/recipe154/600/400",
      title: "Tom Yum Soup #154",
      description:
        "A delicious american style tom yum soup made with fresh ingredients.",
      cookTime: "80 mins",
      cuisine: "Mexican",
      difficulty: "Medium",
      calories: "680 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 155,
      image: "https://picsum.photos/seed/recipe155/600/400",
      title: "Chocolate Cake #155",
      description:
        "A delicious italian style chocolate cake made with fresh ingredients.",
      cookTime: "21 mins",
      cuisine: "Chinese",
      difficulty: "Hard",
      calories: "763 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Olive Oil"],
    },
    {
      id: 156,
      image: "https://picsum.photos/seed/recipe156/600/400",
      title: "Pancakes #156",
      description:
        "A delicious thai style pancakes made with fresh ingredients.",
      cookTime: "77 mins",
      cuisine: "American",
      difficulty: "Medium",
      calories: "624 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Pepper"],
    },
    {
      id: 157,
      image: "https://picsum.photos/seed/recipe157/600/400",
      title: "Burger #157",
      description:
        "A delicious french style burger made with fresh ingredients.",
      cookTime: "59 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "257 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Garlic"],
    },
    {
      id: 158,
      image: "https://picsum.photos/seed/recipe158/600/400",
      title: "Grilled Salmon #158",
      description:
        "A delicious american style grilled salmon made with fresh ingredients.",
      cookTime: "84 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "684 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 159,
      image: "https://picsum.photos/seed/recipe159/600/400",
      title: "Momos #159",
      description: "A delicious thai style momos made with fresh ingredients.",
      cookTime: "68 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "757 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 160,
      image: "https://picsum.photos/seed/recipe160/600/400",
      title: "Dosa #160",
      description: "A delicious korean style dosa made with fresh ingredients.",
      cookTime: "39 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "603 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Garlic"],
    },
    {
      id: 161,
      image: "https://picsum.photos/seed/recipe161/600/400",
      title: "Margherita Pizza #161",
      description:
        "A delicious japanese style margherita pizza made with fresh ingredients.",
      cookTime: "60 mins",
      cuisine: "American",
      difficulty: "Medium",
      calories: "577 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Onion"],
    },
    {
      id: 162,
      image: "https://picsum.photos/seed/recipe162/600/400",
      title: "Chicken Biryani #162",
      description:
        "A delicious korean style chicken biryani made with fresh ingredients.",
      cookTime: "44 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "544 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Pepper"],
    },
    {
      id: 163,
      image: "https://picsum.photos/seed/recipe163/600/400",
      title: "Paneer Butter Masala #163",
      description:
        "A delicious japanese style paneer butter masala made with fresh ingredients.",
      cookTime: "46 mins",
      cuisine: "Indian",
      difficulty: "Medium",
      calories: "814 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Pepper"],
    },
    {
      id: 164,
      image: "https://picsum.photos/seed/recipe164/600/400",
      title: "Caesar Salad #164",
      description:
        "A delicious american style caesar salad made with fresh ingredients.",
      cookTime: "70 mins",
      cuisine: "Japanese",
      difficulty: "Easy",
      calories: "211 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Herbs"],
    },
    {
      id: 165,
      image: "https://picsum.photos/seed/recipe165/600/400",
      title: "Sushi Roll #165",
      description:
        "A delicious italian style sushi roll made with fresh ingredients.",
      cookTime: "66 mins",
      cuisine: "Mexican",
      difficulty: "Easy",
      calories: "636 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Garlic"],
    },
    {
      id: 166,
      image: "https://picsum.photos/seed/recipe166/600/400",
      title: "Pad Thai #166",
      description:
        "A delicious korean style pad thai made with fresh ingredients.",
      cookTime: "47 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "721 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 167,
      image: "https://picsum.photos/seed/recipe167/600/400",
      title: "Butter Chicken #167",
      description:
        "A delicious chinese style butter chicken made with fresh ingredients.",
      cookTime: "41 mins",
      cuisine: "Mexican",
      difficulty: "Medium",
      calories: "269 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 168,
      image: "https://picsum.photos/seed/recipe168/600/400",
      title: "Tacos #168",
      description:
        "A delicious japanese style tacos made with fresh ingredients.",
      cookTime: "85 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "574 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Onion"],
    },
    {
      id: 169,
      image: "https://picsum.photos/seed/recipe169/600/400",
      title: "Veg Fried Rice #169",
      description:
        "A delicious chinese style veg fried rice made with fresh ingredients.",
      cookTime: "44 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "260 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 170,
      image: "https://picsum.photos/seed/recipe170/600/400",
      title: "Pasta Alfredo #170",
      description:
        "A delicious american style pasta alfredo made with fresh ingredients.",
      cookTime: "20 mins",
      cuisine: "Chinese",
      difficulty: "Easy",
      calories: "648 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Pepper"],
    },
    {
      id: 171,
      image: "https://picsum.photos/seed/recipe171/600/400",
      title: "Ramen #171",
      description:
        "A delicious japanese style ramen made with fresh ingredients.",
      cookTime: "77 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "715 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 172,
      image: "https://picsum.photos/seed/recipe172/600/400",
      title: "Falafel #172",
      description:
        "A delicious thai style falafel made with fresh ingredients.",
      cookTime: "41 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "617 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Pepper"],
    },
    {
      id: 173,
      image: "https://picsum.photos/seed/recipe173/600/400",
      title: "Shawarma #173",
      description:
        "A delicious italian style shawarma made with fresh ingredients.",
      cookTime: "45 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "376 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 174,
      image: "https://picsum.photos/seed/recipe174/600/400",
      title: "Tom Yum Soup #174",
      description:
        "A delicious thai style tom yum soup made with fresh ingredients.",
      cookTime: "60 mins",
      cuisine: "Mediterranean",
      difficulty: "Medium",
      calories: "621 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Onion"],
    },
    {
      id: 175,
      image: "https://picsum.photos/seed/recipe175/600/400",
      title: "Chocolate Cake #175",
      description:
        "A delicious japanese style chocolate cake made with fresh ingredients.",
      cookTime: "66 mins",
      cuisine: "French",
      difficulty: "Medium",
      calories: "608 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Olive Oil"],
    },
    {
      id: 176,
      image: "https://picsum.photos/seed/recipe176/600/400",
      title: "Pancakes #176",
      description:
        "A delicious mexican style pancakes made with fresh ingredients.",
      cookTime: "28 mins",
      cuisine: "Thai",
      difficulty: "Hard",
      calories: "292 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Herbs"],
    },
    {
      id: 177,
      image: "https://picsum.photos/seed/recipe177/600/400",
      title: "Burger #177",
      description:
        "A delicious korean style burger made with fresh ingredients.",
      cookTime: "60 mins",
      cuisine: "Japanese",
      difficulty: "Medium",
      calories: "420 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 178,
      image: "https://picsum.photos/seed/recipe178/600/400",
      title: "Grilled Salmon #178",
      description:
        "A delicious italian style grilled salmon made with fresh ingredients.",
      cookTime: "29 mins",
      cuisine: "Thai",
      difficulty: "Easy",
      calories: "600 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Pepper"],
    },
    {
      id: 179,
      image: "https://picsum.photos/seed/recipe179/600/400",
      title: "Momos #179",
      description:
        "A delicious french style momos made with fresh ingredients.",
      cookTime: "76 mins",
      cuisine: "Indian",
      difficulty: "Medium",
      calories: "588 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 180,
      image: "https://picsum.photos/seed/recipe180/600/400",
      title: "Dosa #180",
      description: "A delicious korean style dosa made with fresh ingredients.",
      cookTime: "18 mins",
      cuisine: "Japanese",
      difficulty: "Hard",
      calories: "780 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Onion"],
    },
    {
      id: 181,
      image: "https://picsum.photos/seed/recipe181/600/400",
      title: "Margherita Pizza #181",
      description:
        "A delicious chinese style margherita pizza made with fresh ingredients.",
      cookTime: "56 mins",
      cuisine: "Mexican",
      difficulty: "Hard",
      calories: "646 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Herbs"],
    },
    {
      id: 182,
      image: "https://picsum.photos/seed/recipe182/600/400",
      title: "Chicken Biryani #182",
      description:
        "A delicious indian style chicken biryani made with fresh ingredients.",
      cookTime: "26 mins",
      cuisine: "Thai",
      difficulty: "Easy",
      calories: "814 kcal",
      ingredients: ["Paneer", "Cream", "Tomato", "Garlic"],
    },
    {
      id: 183,
      image: "https://picsum.photos/seed/recipe183/600/400",
      title: "Paneer Butter Masala #183",
      description:
        "A delicious mediterranean style paneer butter masala made with fresh ingredients.",
      cookTime: "17 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "679 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Herbs"],
    },
    {
      id: 184,
      image: "https://picsum.photos/seed/recipe184/600/400",
      title: "Caesar Salad #184",
      description:
        "A delicious indian style caesar salad made with fresh ingredients.",
      cookTime: "14 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "227 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 185,
      image: "https://picsum.photos/seed/recipe185/600/400",
      title: "Sushi Roll #185",
      description:
        "A delicious mediterranean style sushi roll made with fresh ingredients.",
      cookTime: "60 mins",
      cuisine: "Thai",
      difficulty: "Medium",
      calories: "743 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Pepper"],
    },
    {
      id: 186,
      image: "https://picsum.photos/seed/recipe186/600/400",
      title: "Pad Thai #186",
      description:
        "A delicious mexican style pad thai made with fresh ingredients.",
      cookTime: "19 mins",
      cuisine: "Italian",
      difficulty: "Medium",
      calories: "348 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Onion"],
    },
    {
      id: 187,
      image: "https://picsum.photos/seed/recipe187/600/400",
      title: "Butter Chicken #187",
      description:
        "A delicious korean style butter chicken made with fresh ingredients.",
      cookTime: "30 mins",
      cuisine: "Mediterranean",
      difficulty: "Easy",
      calories: "417 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Olive Oil"],
    },
    {
      id: 188,
      image: "https://picsum.photos/seed/recipe188/600/400",
      title: "Tacos #188",
      description:
        "A delicious american style tacos made with fresh ingredients.",
      cookTime: "36 mins",
      cuisine: "French",
      difficulty: "Easy",
      calories: "700 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Herbs"],
    },
    {
      id: 189,
      image: "https://picsum.photos/seed/recipe189/600/400",
      title: "Veg Fried Rice #189",
      description:
        "A delicious chinese style veg fried rice made with fresh ingredients.",
      cookTime: "62 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "711 kcal",
      ingredients: ["Lettuce", "Croutons", "Parmesan", "Onion"],
    },
    {
      id: 190,
      image: "https://picsum.photos/seed/recipe190/600/400",
      title: "Pasta Alfredo #190",
      description:
        "A delicious korean style pasta alfredo made with fresh ingredients.",
      cookTime: "44 mins",
      cuisine: "Italian",
      difficulty: "Hard",
      calories: "308 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Olive Oil"],
    },
    {
      id: 191,
      image: "https://picsum.photos/seed/recipe191/600/400",
      title: "Ramen #191",
      description:
        "A delicious indian style ramen made with fresh ingredients.",
      cookTime: "57 mins",
      cuisine: "Indian",
      difficulty: "Medium",
      calories: "436 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 192,
      image: "https://picsum.photos/seed/recipe192/600/400",
      title: "Falafel #192",
      description:
        "A delicious french style falafel made with fresh ingredients.",
      cookTime: "27 mins",
      cuisine: "Chinese",
      difficulty: "Medium",
      calories: "484 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 193,
      image: "https://picsum.photos/seed/recipe193/600/400",
      title: "Shawarma #193",
      description:
        "A delicious french style shawarma made with fresh ingredients.",
      cookTime: "34 mins",
      cuisine: "Korean",
      difficulty: "Hard",
      calories: "216 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Onion"],
    },
    {
      id: 194,
      image: "https://picsum.photos/seed/recipe194/600/400",
      title: "Tom Yum Soup #194",
      description:
        "A delicious korean style tom yum soup made with fresh ingredients.",
      cookTime: "79 mins",
      cuisine: "French",
      difficulty: "Easy",
      calories: "744 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Herbs"],
    },
    {
      id: 195,
      image: "https://picsum.photos/seed/recipe195/600/400",
      title: "Chocolate Cake #195",
      description:
        "A delicious korean style chocolate cake made with fresh ingredients.",
      cookTime: "52 mins",
      cuisine: "Korean",
      difficulty: "Easy",
      calories: "525 kcal",
      ingredients: ["Chicken", "Rice", "Spices", "Olive Oil"],
    },
    {
      id: 196,
      image: "https://picsum.photos/seed/recipe196/600/400",
      title: "Pancakes #196",
      description:
        "A delicious french style pancakes made with fresh ingredients.",
      cookTime: "37 mins",
      cuisine: "Korean",
      difficulty: "Hard",
      calories: "422 kcal",
      ingredients: ["Noodles", "Peanuts", "Egg", "Olive Oil"],
    },
    {
      id: 197,
      image: "https://picsum.photos/seed/recipe197/600/400",
      title: "Burger #197",
      description:
        "A delicious chinese style burger made with fresh ingredients.",
      cookTime: "50 mins",
      cuisine: "American",
      difficulty: "Hard",
      calories: "388 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 198,
      image: "https://picsum.photos/seed/recipe198/600/400",
      title: "Grilled Salmon #198",
      description:
        "A delicious thai style grilled salmon made with fresh ingredients.",
      cookTime: "72 mins",
      cuisine: "Korean",
      difficulty: "Medium",
      calories: "319 kcal",
      ingredients: ["Tomato", "Cheese", "Basil", "Pepper"],
    },
    {
      id: 199,
      image: "https://picsum.photos/seed/recipe199/600/400",
      title: "Momos #199",
      description:
        "A delicious japanese style momos made with fresh ingredients.",
      cookTime: "53 mins",
      cuisine: "American",
      difficulty: "Easy",
      calories: "284 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Herbs"],
    },
    {
      id: 200,
      image: "https://picsum.photos/seed/recipe200/600/400",
      title: "Dosa #200",
      description: "A delicious thai style dosa made with fresh ingredients.",
      cookTime: "84 mins",
      cuisine: "Mediterranean",
      difficulty: "Easy",
      calories: "378 kcal",
      ingredients: ["Rice", "Nori", "Salmon", "Garlic"],
    },
  ];

  
  return (
    <div>
      <nurseData.Provider value={allrecipedData}>{children}</nurseData.Provider>
    </div>
  );
};

export default Nursedata;
